# Generated by Django 3.0 on 2019-02-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('returns', models.DecimalField(decimal_places=2, max_digits=9)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(max_length=10)),
                ('invest_date', models.DateField(verbose_name='date_invested')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('password_confirm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('contrib_date', models.DateField(verbose_name='date_published')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamics.User')),
            ],
        ),
    ]
