# Generated by Django 3.0 on 2019-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='url',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='investments',
            name='url',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
