# Generated by Django 3.0 on 2019-02-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0003_auto_20190227_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='total',
        ),
    ]
