# Generated by Django 3.0 on 2019-02-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0003_auto_20190208_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_confirm',
            field=models.CharField(max_length=500),
        ),
    ]
